#+title: leaf-defaults.el
#+author: Naoya Yamashita

Shareable default configurations for leaf.el packages.

[[https://github.com/conao3/leaf-defaults.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/leaf-defaults.el.svg?style=flat-square]]
[[https://github.com/conao3/leaf-defaults.el/releases][https://img.shields.io/github/tag/conao3/leaf-defaults.el.svg?style=flat-square]]
[[https://github.com/conao3/leaf-defaults.el/actions][https://github.com/conao3/leaf-defaults.el/workflows/Main%20workflow/badge.svg]]

* Overview

leaf-defaults provides a =:defaults= keyword for [[https://github.com/conao3/leaf.el][leaf.el]] that enables users to apply pre-configured settings to packages. This allows you to:

- Share recommended configurations with other users
- Reduce boilerplate in your init.el
- Apply curated defaults from the community

* Requirements

- Emacs 26.1 or later
- [[https://github.com/conao3/leaf.el][leaf.el]] 4.1 or later
- [[https://github.com/conao3/leaf-keywords.el][leaf-keywords]] 1.1 or later

* Installation

Using leaf.el:

#+begin_src emacs-lisp
(leaf leaf-defaults
  :ensure t
  :config
  (leaf-defaults-init))
#+end_src

* Usage

** The :defaults Keyword

The =:defaults= keyword calls dynamically named functions that apply pre-configured settings to a package. When set to =t=, it uses the built-in leaf defaults. You can also specify custom configuration providers.

*** Basic Usage

Apply built-in defaults:

#+begin_src emacs-lisp
(leaf company
  :ensure t
  :defaults t)
#+end_src

This expands to:

#+begin_src emacs-lisp
(prog1 'company
  (leaf-handler-package company company nil)
  (leaf-keywords-defaults--leaf/company))
#+end_src

*** Custom Configuration Providers

Specify one or more configuration providers:

#+begin_src emacs-lisp
;; Single provider
(leaf helm
  :ensure t
  :defaults conao3)

;; Multiple providers
(leaf helm
  :ensure t
  :defaults conao3 other-user)
#+end_src

*** Combining with Conditions

The =:defaults= keyword respects conditional keywords:

#+begin_src emacs-lisp
(leaf helm
  :when (display-graphic-p)
  :ensure t
  :defaults t)
#+end_src

** Included Package Configurations

The package ships with sensible defaults for common packages:

- =company= - Completion framework with optimized settings
- =flycheck= - On-the-fly syntax checking
- =ivy= / =swiper= / =counsel= - Completion and search
- =paren= - Parenthesis highlighting
- Built-in packages: =cus-edit=, =cus-start=, =delsel=, =files=, =simple=, =startup=

Load a bundle of base configurations:

#+begin_src emacs-lisp
(leaf-defaults-recipe--leaf-defaults/base)
#+end_src

* Contributing

Contributions are welcome. Please open an issue or submit a pull request.

** Development Setup

Install [[https://github.com/conao3/keg][keg]] for testing:

#+begin_src shell
git clone https://github.com/conao3/keg ~/.keg
export PATH="$HOME/.keg/bin:$PATH"
#+end_src

** Workflow

#+begin_src shell
git checkout -b feature-branch
# Make your changes
make test
git commit -am "Description of changes"
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/leaf-defaults.el/blob/master/LICENSE][LICENSE]] for details.

Copyright (C) Naoya Yamashita
